; The very slick RAK wireless RAK 4631 / 4630 board - Unified firmware for 5005/19003, with or without OLED RAK 1921
[env:rak4631_var]
extends = nrf52840_base
board = wiscore_rak4631
board_level = pr
board_check = true
build_type = release
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/diy/nswcrs
  -D RAK_4631
  ; -DMESHTASTIC_USE_EINK_UI=0
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_SX127X=1
  -DRADIOLIB_EXCLUDE_LR11X0=1
build_src_filter = ${nrf52_base.build_src_filter} \
  +<../variants/nrf52840/diy/nswcrs> \
  +<mesh/eth/> \
  +<mesh/api/> \
  +<mqtt/> \
  -<graphics/EInkDisplay2.cpp> \
  -<graphics/EInkDynamicDisplay.cpp> \
  -<graphics/fonts/EinkDisplayFonts.cpp>
lib_deps = 
  ${nrf52840_base.lib_deps}
  ${nrf52_networking_base.lib_deps}
  melopero/Melopero RV3028@^1.1.0
  https://github.com/RAKWireless/RAK13800-W5100S/archive/1.0.2.zip
  ; rakwireless/RAKwireless NCP5623 RGB LED library@^1.0.2
  ; beegee-tokyo/RAK12035_SoilMoisture@^1.0.4
  # renovate: datasource=git-refs depName=RAK12034-BMX160 packageName=https://github.com/RAKWireless/RAK12034-BMX160 gitBranch=main
  https://github.com/RAKWireless/RAK12034-BMX160/archive/dcead07ffa267d3c906e9ca4a1330ab989e957e2.zip


[env:nswcrs]
extends = env:rak4631_var
build_type = release
board_level = extra

; upload_protocol = stlink
;upload_protocol = jlink
;debug_tool = jlink

build_flags =
  ${env:rak4631_var.build_flags}
  ; -D GPS_L76K
; build_unflags = -DHAS_NCP5623
build_src_filter = ${env:rak4631_var.build_src_filter}


[env:nswcrs_flamingo]
extends = env:rak4631_var
board_level = extra

build_flags =
  ${env:rak4631_var.build_flags}
  -D FLAMINGO
  -D FLAMINGO_RT_LED
  ; -DPIN_LED_RT_R=3
  ; -DPIN_LED_RT_G=2
  ; -DPIN_LED_RT_B=28 # not populated
  -D FLAMINGO_CONNECTION_LED
  ; -DPIN_LED_CONN_R=30
  ; -DPIN_LED_CONN_G=26
  ; -DPIN_LED_CONN_B=29 # not populated
  ; -D FLAMINGO_BLINKY
  -D MESHTASTIC_EXCLUDE_MQTT
  ;-D MESHTASTIC_EXCLUDE_GPS
  ; -D GPS_L76K
; build_unflags = -DHAS_NCP5623

; lib_deps =
;   ${env:rak4631.lib_deps}
;   https://github.com/geeksville/Armduino-Semihosting.git#35b538fdf208c3530c1434cd099a08e486672ee4


[env:nswcrs_flamingo_slink]
extends = env:nswcrs_flamingo
board_level = extra

upload_protocol = stlink
;upload_protocol = jlink
;debug_tool = jlink

build_flags =
  ${env:nswcrs_flamingo.build_flags}
  -D FLAMINGO_SLINK
  -DFLAMINGO_SLINK_RXD=PIN_SERIAL1_TX ; yes, invert them. 
  -DFLAMINGO_SLINK_TXD=PIN_SERIAL1_RX
  ;-D FLAMINGO_SLINK_DEBUG
  ;-D MESHTASTIC_EXCLUDE_GPS
  ;-D LORA_DISABLE_SENDING
  ;-D LORA_DISABLE_RECEIVE

  
; build_unflags =
;   -D GPS_L76K

lib_deps =
  ${env:nswcrs_flamingo.lib_deps}

